### ISSUE TITLE
bug #1

### ISSUE THREAD

**Issue by Kwaskoff** [fuseio/fusebox-backend#311]
steps for repeat:
1. git clone https://github.com/fuseio/fusebox-backend.git
2. npm install
3. a. cp .env.example .env
  b. cp apps/charge-api-service/.env.example apps/charge-api-service/.env
  c. cp apps/charge-network-service/.env.example apps/charge-network-service/.env
  d. cp apps/charge-relay-service/.env.example apps/charge-relay-service/.env
4.  npm run docker:dev

answer: 
```
> charge-backend@0.0.1 docker:dev
> docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

ERROR: Service 'charge-smart-wallets-service' depends on service 'centrifugo' which is undefined.
```

**Comment by Kwaskoff** [comment]
Make sure you update the .env files with necessary variable values before proceeding to the next step. - I don't know details =(

**Comment by LiorAgnin** [comment]
Hi @Kwaskoff,
The issue has been resolved. We've updated the necessary configurations to ensure the 'centrifugo' service is properly defined and included in the docker-compose setup. This should allow the 'charge-smart-wallets-service' to start correctly. Please try the steps again and let us know if you encounter any further problems.

**Comment by LiorAgnin** [comment]
Hi @Kwaskoff,
The issue has been resolved. We've updated the necessary configurations to ensure the 'centrifugo' service is properly defined and included in the docker-compose setup. This should allow the 'charge-smart-wallets-service' to start correctly. Please try the steps again and let us know if you encounter any further problems.
